version: '3.8'

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    environment:
      POSTGRES_DB: foodgram_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: Kuzia_26148
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d foodgram_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    container_name: foodgram-backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - .:/app
      - ./staticfiles:/app/static
      - ./media:/app/media
    environment:
      - POSTGRES_DB=foodgram_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=Kuzia_26148
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-yndk(x4#&3mf06--)(k^^v%8^$9_kq&=##6eumoha+=hzjae^b
      - DEBUG=False
      - ALLOWED_HOSTS=foodgramkuzmich.zapto.org,89.169.175.209,localhost,127.0.0.1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local